In [1]:
import joblib
df = joblib.load("../learning_notebooks/data/df.pkl")
rf_model = joblib.load("../learning_notebooks/model/rf_model.pkl")

In [2]:
df

,Gender,ApplicantIncome,CoapplicantIncome,Loan_Amount,Loan_Amount_Term,Credit_History,TotalIncome,LoanIncomeRatio,Married_Yes,Dependents_1,Dependents_2,Dependents_3+,Education_Not Graduate,Self_Employed_Yes,Loan_Status_Y,IncomeGroup_medium,IncomeGroup_high,IncomeGroup_veryhigh
0,1,5849,0,146,360,1,5849,0,0,0,0,0,0,0,1,0,0,1
1,1,4583,1508,128,360,1,6091,0,1,1,0,0,0,0,0,0,0,1
2,1,3000,0,66,360,1,3000,0,1,0,0,0,0,1,1,1,0,0
3,1,2583,2358,120,360,1,4941,0,1,0,0,0,1,0,1,0,1,0
4,1,6000,0,141,360,1,6000,0,0,0,0,0,0,0,1,0,0,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
609,0,2900,0,71,360,1,2900,0,0,0,0,0,0,0,1,1,0,0
610,1,4106,0,40,180,1,4106,0,1,0,0,1,0,0,1,0,1,0
611,1,8072,240,253,360,1,8312,0,1,1,0,0,0,0,1,0,0,1
612,1,7583,0,187,360,1,7583,0,1,0,1,0,0,0,1,0,0,1


In [3]:
X=df.drop('Loan_Status_Y',axis=1)
y=df['Loan_Status_Y']

In [4]:
# cross validation

In [5]:
# k fold code 
from sklearn.model_selection import cross_val_score
score=cross_val_score(
    rf_model, 
    X,
    y,
    cv=5, 
    scoring='f1'
)

In [6]:
score

array([0.84324324, 0.8172043 , 0.86021505, 0.84393064, 0.86666667])

In [7]:
score.mean()

np.float64(0.846251980117354)

In [8]:
from sklearn.model_selection import StratifiedKFold
skf=StratifiedKFold(n_splits=5,shuffle=True,random_state=42)

In [9]:
skf

StratifiedKFold(n_splits=5, random_state=42, shuffle=True)

In [10]:
# learning curve

In [11]:
# plot learning curve

In [12]:
from sklearn.model_selection import learning_curve
import numpy as np
train_sizes,train_score,val_score=learning_curve(
    rf_model, 
    X, 
    y, 
    cv=5, 
    scoring='f1', 
    train_sizes=np.linspace(0.1,1.0,5)
)
train_mean=train_score.mean(axis=1) 
val_mean=val_score.mean(axis=1)

In [13]:
train_mean

array([1., 1., 1., 1., 1.])

In [14]:
val_mean

array([0.81397252, 0.82853299, 0.82877917, 0.85331868, 0.84498569])

In [15]:
# error analysis